version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:2345
    volumes:
      - .:/clean_web
    env_file: .env
    security_opt:
      - seccomp:unconfined
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      POSTGRES_USERNAME: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 54322:5432
    volumes:
      - user_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  user_db:
